/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as RegistryIdRouteImport } from './routes/registry.$id'
import { Route as DesignSlugRouteImport } from './routes/design.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const RegistryIdRoute = RegistryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegistryRoute,
} as any)
const DesignSlugRoute = DesignSlugRouteImport.update({
  id: '/design/$slug',
  path: '/design/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/designs': typeof DesignsRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/registry': typeof RegistryRouteWithChildren
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design/$slug': typeof DesignSlugRoute
  '/registry/$id': typeof RegistryIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/designs': typeof DesignsRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/registry': typeof RegistryRouteWithChildren
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design/$slug': typeof DesignSlugRoute
  '/registry/$id': typeof RegistryIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/designs': typeof DesignsRoute
  '/help': typeof HelpRoute
  '/learn': typeof LearnRoute
  '/registry': typeof RegistryRouteWithChildren
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/design/$slug': typeof DesignSlugRoute
  '/registry/$id': typeof RegistryIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/auth'
    | '/author'
    | '/designs'
    | '/help'
    | '/learn'
    | '/registry'
    | '/search'
    | '/sources'
    | '/topics'
    | '/admin'
    | '/favorites'
    | '/settings'
    | '/api/chat'
    | '/blog/$slug'
    | '/design/$slug'
    | '/registry/$id'
    | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/auth'
    | '/author'
    | '/designs'
    | '/help'
    | '/learn'
    | '/registry'
    | '/search'
    | '/sources'
    | '/topics'
    | '/admin'
    | '/favorites'
    | '/settings'
    | '/api/chat'
    | '/blog/$slug'
    | '/design/$slug'
    | '/registry/$id'
    | '/topics/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/advisor'
    | '/auth'
    | '/author'
    | '/designs'
    | '/help'
    | '/learn'
    | '/registry'
    | '/search'
    | '/sources'
    | '/topics'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/blog/$slug'
    | '/design/$slug'
    | '/registry/$id'
    | '/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  AuthRoute: typeof AuthRoute
  AuthorRoute: typeof AuthorRoute
  DesignsRoute: typeof DesignsRoute
  HelpRoute: typeof HelpRoute
  LearnRoute: typeof LearnRoute
  RegistryRoute: typeof RegistryRouteWithChildren
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DesignSlugRoute: typeof DesignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/registry/$id': {
      id: '/registry/$id'
      path: '/$id'
      fullPath: '/registry/$id'
      preLoaderRoute: typeof RegistryIdRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/design/$slug': {
      id: '/design/$slug'
      path: '/design/$slug'
      fullPath: '/design/$slug'
      preLoaderRoute: typeof DesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RegistryRouteChildren {
  RegistryIdRoute: typeof RegistryIdRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryIdRoute: RegistryIdRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  AuthRoute: AuthRoute,
  AuthorRoute: AuthorRoute,
  DesignsRoute: DesignsRoute,
  HelpRoute: HelpRoute,
  LearnRoute: LearnRoute,
  RegistryRoute: RegistryRouteWithChildren,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  TopicsRoute: TopicsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  DesignSlugRoute: DesignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
