-- Superseded by 20260711090000_source_watchers.sql.
--
-- This migration was generated as a byte-for-byte duplicate of 20260711090000 (same tables,
-- backfill, indexes, RLS, trigger and views). Both carried a bare `CREATE TABLE`, so replaying
-- the full migration set against a clean database failed with:
--
--   ERROR: relation "source_watchers" already exists (SQLSTATE 42P07)
--
-- It never surfaced on the original project, where the objects already existed. Reduced to a
-- no-op so the schema is reproducible from migrations alone; the original is left untouched so
-- history stays consistent on databases that already recorded this version.
